[profile.default]
src = "src"
test = "test"
out = "out"
libs = ["lib"]
solc_version = "0.8.24"
via_ir = true
optimizer = true
optimizer_runs = 2000

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true

[fuzz]
runs = 128

[invariant]
runs = 128
depth = 15

[lint]
exclude_lints = ["asm-keccak256"]
